### ISSUE TITLE
Implement a CodeQL query that checks for invocations of Vertx.vertx()

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-codeql-queries#14]
# Task Description

We need to implement a CodeQL query that checks for invocations of `Vertx.vertx()`.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [ ] Implement a query.
* [ ] Create a query help file.
* [ ] Test the fix.
  * [ ] Implement a test case.
    * [ ] Add Java class(es) that contains the vulnerability.
    * [ ] Add Java class(es) that do not contain the vulnerability.
    * [ ] Set up a `.qlref` file.
    * [ ] Set up an `.expected` file and make sure the results only contain findings in the vulnerable class(es).
    * [ ] Set up an `options` file.
    * [ ] Set up a `pom.xml` file.
* [ ] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of: 
* Relates to:

# Resources

# Useful Links

# Points of Contact
