### ISSUE TITLE
Investigate how to set up tests for CodeQL queries

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-codeql-queries#2]
# Task Description

# Open Questions

# Notes

* Create a directory for the test.
* Create a `pom.xml` with the required Maven dependencies.
* Create an `options` file in the test directory that looks somewhat like this:
```
//semmle-extractor-options: --javac-args -cp ${testdir}/../../stubs/ -source 17
```
* Invoke the [makeStubs](https://github.com/github/codeql/blob/main/java/ql/src/utils/stub-generator/makeStubs.py) to generate stubs for the required sources of your dependencies, like this:
```
carlspring@carlspring:/java/vertx-codeql-queries/ql/test$ mkdir stubs
carlspring@carlspring:/java/vertx-codeql-queries/ql/test$ cd InsecureCorsHttpOrigin
carlspring@carlspring:/java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsHttpOrigin$ python3 /java/codeql/java/ql/src/utils/stub-generator/makeStubs.py . ../../stubs/ pom.xml 
```
* Create a `.qlref` listing the the query to be tested. (The file must have the same base name as that of the `.ql` to be tested).
* Add code. (Note that the code should be placed directly under the root of the test directory. It will not work if you have a structure such as `src/main/java`).
  * Add `bad` code implementation.
  * Add `good` code implementation.
* Add an `.expected` file with the expected output. (The file must have the same base name as that of the `.ql` to be tested).

# Task List

The following tasks will need to be carried out:
* [x] Investigate what needs to be done.
* [x] Add stubs.
* [x] Implement test cases
  * [x] Implement a test case for `InsecureCorsHttpOrigin`.
  * [x] Implement a test case for `InsecureCorsWildcardOrigin`.
  * [x] Implement a test case for `InsecureHttpServer`.
* [x] Document the process.

# Useful Commands

* To create a CodeQL database execute the following inside the root of the `vertx-vulns` repository:
```
codeql database create vertx-vulns --language=java
```

* To execute a single CodeQL query against the database, execute:
```
codeql query run -v --database=/java/vertx-vulns/vertx-vulns/ InsecureHttpServer.ql
```

* To execute multiple CodeQL queries in parallel against the database, execute:
```
codeql database run-queries -- /java/vertx-vulns/vertx-vulns *.ql
```

* To run the tests:
```
carlspring@carlspring:/java/vertx-codeql-queries/ql/test$ codeql test run . --additional-packs=../src
Executing 3 tests in 3 directories.
Extracting test database in /java/vertx-codeql-queries/ql/test/query-tests/InsecureHttpServer.
Compiling queries in /java/vertx-codeql-queries/ql/test/query-tests/InsecureHttpServer.
Executing tests in /java/vertx-codeql-queries/ql/test/query-tests/InsecureHttpServer.
[1/3 comp 9.5s eval 943ms] PASSED /java/vertx-codeql-queries/ql/test/query-tests/InsecureHttpServer/InsecureHttpServer.qlref
Extracting test database in /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsHttpOrigin.
Compiling queries in /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsHttpOrigin.
Executing tests in /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsHttpOrigin.
[2/3 comp 124ms eval 459ms] PASSED /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsHttpOrigin/InsecureCorsHttpOrigin.qlref
Extracting test database in /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsWildcardOrigin.
Compiling queries in /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsWildcardOrigin.
Executing tests in /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsWildcardOrigin.
[3/3 comp 104ms eval 476ms] PASSED /java/vertx-codeql-queries/ql/test/query-tests/InsecureCorsWildcardOrigin/InsecureCorsWildcardOrigin.qlref
All 3 tests passed.
```

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:

# Resources

# Useful Links

* [CodeQL: Testing Cusgtom Queries](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/testing-custom-queries)
* [CodeQL: Query Reference Files](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/query-reference-files)

# Points of Contact

* @carlspring
