### ISSUE TITLE
Implement a CodeQL rule for CORS misconfigurations that allow wildcard origins

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-codeql-queries#4]
# Task Description

As a follow-up of carlspring/vertx-vulns#8, we should implement a CodeQL query that checks for CORS misconfigurations that allow wildcard origins.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Implement the query.
* [x] [Set up query annotations](https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/).
* [x] Provide a help file.
* [x] Test the fix.
* [x] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
* Depends on: 
* Is a follow-up of:
  * carlspring/vertx-vulns#8
* Is required for:
  * #1
* Relates to:
  * #4

# Resources

# Useful Links

* [CodeQL: Set up query annotations](https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/)
* [CodeQL: Defining the results of a query](https://codeql.github.com/docs/writing-codeql-queries/defining-the-results-of-a-query/#adding-a-link-to-the-similar-file)

# Points of Contact

* @carlspring

**Comment by carlspring** [comment]
Implemented.
