### ISSUE TITLE
Implement a CodeQL rule for cases where WebClient.create is used without setting a WebClientOptions with an explicit setIdleTimeout

### ISSUE THREAD

**Issue by carlspring** [carlspring/vertx-codeql-queries#6]
# Task Description

As a follow-up of carlspring/vertx-vulns#18, we need to implement a CodeQL rule for cases where `WebClient.create` is used without setting a `WebClientOptions` with an explicit `setIdleTimeout`.

# Open Questions

* What should be the severity of this?

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Implement the query.
* [x] [Set up query annotations](https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/).
* [ ] Provide a help file.
* [ ] Test the fix.
* [ ] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of:
* Depends on: 
* Is a follow-up of:
  * carlspring/vertx-vulns#6
* Is required for:
  * #1
* Relates to:

# Resources

# Useful Links

* [CodeQL: Set up query annotations](https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/)
* [CodeQL: Defining the results of a query](https://codeql.github.com/docs/writing-codeql-queries/defining-the-results-of-a-query/#adding-a-link-to-the-similar-file)

# Points of Contact

* @carlspring
